# Generated by Django 5.0 on 2024-02-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customer_additional_field_customer_receive_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
