# Generated by Django 5.0 on 2024-02-29 23:03

import polls.models.enum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=polls.models.enum.PaymentType.choices, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=polls.models.enum.ProductStatus.choices, default=('offline', 'Offline'), max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(choices=polls.models.enum.Supplier.choices, max_length=50),
        ),
    ]
